[tool.poetry]
name = "sql-dynamic"
version = "0.1.0"
description = ""
authors = ["sahil  <returnofsahil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg2 = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
